server:
  port: 8081

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
    instance-id: ${spring.application.name}:${server.port}

spring:
  application:
    name: user-client

logging:
  level:
    com.lee: debug

user-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000


feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能


