server:
  port: 10086 # 端口
spring:
  application:
    name: eureka-server1 # 应用名称，会在Eureka中显示
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 #默认30秒，生产环境不需要修改
  server:
    enable-self-preservation: false #开发阶段我们都会关闭自我保护模式
    eviction-interval-timer-in-ms: 1000 #默认每隔60秒对所有失效的服务（超过90秒未响应）进行剔除

