
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: 123
  application:
    name: user-service

mybatis:
  type-aliases-package: com.lee.domain

server:
  port: 8082

eureka:
  client:
    service-url: # EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
